version: '3'
services:
  json-server:
    build: .
    image: node:13.7.0-alpine
    tty: true
    working_dir: /usr/src/app
    stdin_open: true
    restart: unless-stopped
    command: npm run server
    ports:
      - "3333:3333"

