version: "3"
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "4200:80"
  json-server:
      image: clue/json-server
      volumes:
        - ./db.json:/data/db.json
      ports:
      - "3333:80"
